### ISSUE TITLE
Page layout style

### ISSUE THREAD

**Issue by nsylv** [aluo-x/813_site#19]
**Feedback:**
The static dark gray background doesn't do anything
The amount of whitespace is nice

**Possible solutions:**
1.  Color code the tabs and the background (make sure each tab also has a lighter "unselected" color)
2.  Make canvas fill whole screen and don't show dark gray background at all

**Comment by nsylv** [comment]
Personally I like the idea of color-coding the tabs and background, and also maybe making the canvas a little bit bigger (we don't need the currently dark-gray space to take up so much room)

**Comment by ramimanna** [comment]
Went with option 2 (for now). I think it looks good. Thoughts on closing this issue?

**Comment by nsylv** [comment]
LGTM
