### ISSUE TITLE
add a delete button in the modal / way to delete a table entry 

### ISSUE THREAD

**Issue by ramimanna** [aluo-x/813_site#25]

**Comment by nsylv** [comment]
I spent about an hour trying to get this to work but was having trouble getting firestore .delete() to work  :(

**Comment by ramimanna** [comment]
:(

**Comment by nsylv** [comment]
Issue was with the button action triggering before executing the delete

Not sure if that  makes sense, but bottom line is `event.preventDefault()` to the rescue
