### ISSUE TITLE
overview tiles responsiveness issue

### ISSUE THREAD

**Issue by ramimanna** [aluo-x/813_site#26]
if you make the window smaller in width, it is responsive just fine, but if you then make it wider again, it doesn't go back to what it was originally

**Comment by aluo-x** [comment]
I believe this only affects the stats page. But it is because the graphs use the canvas element

**Comment by ramimanna** [comment]
yup, have any ideas on how to fix this?

**Comment by nsylv** [comment]
I think this is resolved, feel free to reopen if it isn't
