### ISSUE TITLE
Roles should be multiselect like breeds but is currently single select. Also, Roles don't currently save on edit.

### ISSUE THREAD

**Issue by ramimanna** [aluo-x/813_site#35]

**Comment by ramimanna** [comment]
Gotchu, was being confused about that block of code :p

Also, in terms of UI, I was thinking 3 checkboxes for the roles, because a select2 multiselect seems overkill

**Comment by nsylv** [comment]
Completely agree.  Once I fix up my hacky thing then it should work fine!

**Comment by nsylv** [comment]
A little more complicated than I thought, but seems resolved  :)

Feel free to re-open if you find bugs with the data saving!
