### ISSUE TITLE
Adding too large of a picture silently fails

### ISSUE THREAD

**Issue by nsylv** [aluo-x/813_site#43]
If you attempt to upload a big picture it will fail any edits you make to the animal, and the only way to know is via the console

**Comment by ramimanna** [comment]
Oh interesting, could add size limits or do some kind of dynamic resizing if possible

**Comment by nsylv** [comment]
I feel like dynamic resizing would be the best UX, but also since this is a shallow implementation I dont know if it matters too much and we can just say "use a small picture"

**Comment by nsylv** [comment]
@ramimanna   I think this is resolved now  :)
