### ISSUE TITLE
Adding too many people to the table results in weird formatting

### ISSUE THREAD

**Issue by nsylv** [aluo-x/813_site#7]
See the bottom of this image ("Showing 1 to 9 of 9" runs off of the bottom of the page):

![bad_formatting](https://user-images.githubusercontent.com/8961613/38977056-240ef9b6-4381-11e8-9d90-8a71f1f5e6da.png)

**Comment by aluo-x** [comment]
Looking into this

**Comment by ramimanna** [comment]
I believe I fixed this with my most recent changes involving expanding the main container to full screen and improving the table layout. Is anyone still able to reproduce this bug?

**Comment by nsylv** [comment]
I know longer see it on my end!
