### ISSUE TITLE
Tables are different sizes

### ISSUE THREAD

**Issue by nsylv** [aluo-x/813_site#8]
Click through each of the tables tabs (animals -> people -> events) and note that the size of the canvas changes for each one

**Comment by aluo-x** [comment]
A very odd effect is that the sidebar also seems to be changing size for some reason. Is set to 15%, but it varies by a few pixels on each tab.

**Comment by aluo-x** [comment]
Tried this in Chrome in responsive view, cannot reproduce. 
But in normal Chrome it is very obvious. Possible browser bug?

**Comment by aluo-x** [comment]
Should be fixed now

**Comment by nsylv** [comment]
Verified working in Firefox - nice work!
